# Generated by Django 2.1 on 2019-07-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190709_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Completed_project',
            field=models.TextField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sponsorship',
            field=models.TextField(blank=True, max_length=225, null=True),
        ),
    ]
