# Generated by Django 2.1 on 2019-07-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190709_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='UserClassfication',
            field=models.CharField(blank=True, choices=[('e', 'Engineers'), ('d', 'Doctors'), ('r', 'Researchers'), ('en', 'Entrepreneur'), ('aca', 'Academician')], max_length=5, null=True),
        ),
    ]
