# Generated by Django 2.1 on 2019-07-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userclassfication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userclassfication',
            old_name='UserClassfication',
            new_name='USER_CHOICES',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='UserClassfication',
        ),
        migrations.AddField(
            model_name='profile',
            name='USER_CHOICES',
            field=models.CharField(blank=True, choices=[('1', 'Engineers'), ('2', 'Doctors'), ('3', 'Researchers'), ('4', 'Entrepreneur'), ('5', 'Academician')], max_length=5, null=True),
        ),
    ]
