# Generated by Django 2.1 on 2019-07-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190715_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userclassfication',
            old_name='USER_CHOICES',
            new_name='UserClassfication',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='USER_CHOICES',
        ),
        migrations.AddField(
            model_name='profile',
            name='UserClassfication',
            field=models.CharField(blank=True, choices=[('e', 'Engineers'), ('d', 'Doctors'), ('r', 'Researchers'), ('en', 'Entrepreneur'), ('aca', 'Academician')], max_length=5, null=True),
        ),
    ]
