# Generated by Django 2.1 on 2019-07-15 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190715_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userclassfication',
            name='UserClassfication',
        ),
        migrations.RemoveField(
            model_name='userclassfication',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserClassfication',
        ),
    ]
