# Generated by Django 2.1 on 2019-07-22 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
