# Generated by Django 2.1 on 2019-07-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
