# Generated by Django 2.1 on 2019-07-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190716_0519'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='post',
            name='document',
            field=models.FileField(default='', upload_to='documents/'),
        ),
    ]
