# Generated by Django 2.1 on 2019-07-17 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post1'),
    ]

    operations = [
        migrations.AddField(
            model_name='post1',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='blog.Post'),
        ),
    ]
