# Generated by Django 2.1 on 2019-07-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190717_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderation', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='post1',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post1',
            name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='moderation',
        ),
        migrations.DeleteModel(
            name='Post1',
        ),
    ]
