# Generated by Django 2.1 on 2019-07-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190717_1035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Moderation',
        ),
        migrations.AddField(
            model_name='post',
            name='moderation',
            field=models.BooleanField(default=False),
        ),
    ]
