# Generated by Django 2.1 on 2019-07-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_moderation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='moderation',
        ),
    ]
