# Generated by Django 2.1 on 2019-07-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_delete_moderation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announce',
            name='moderation',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
