# Generated by Django 2.1 on 2019-07-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190720_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announce',
            name='moderation',
            field=models.BooleanField(default=False),
        ),
    ]
