# Generated by Django 2.1 on 2019-07-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20190720_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
